### ISSUE TITLE
Selected tab should be displayed full

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#16]
<img width="480" alt="Screenshot 2021-07-23 at 00 24 32" src="https://user-images.githubusercontent.com/7249484/126711506-fe2cebb6-b82c-4005-98d4-9e0faf399b6f.png">
<img width="462" alt="Screenshot 2021-07-23 at 00 24 36" src="https://user-images.githubusercontent.com/7249484/126711509-28dfd2c6-aeff-4871-9696-146150ccc7c8.png">

**Comment by KatsiarynaV** [comment]
the text shouldn't move and the switcher size shouldn't change
![gif05](https://user-images.githubusercontent.com/68267190/127813808-a5e88fd1-a9d8-486c-bb05-ccdc882252ed.gif)
![07](https://user-images.githubusercontent.com/68267190/127814171-9191c9ef-edb2-49f4-8806-9a41c08e6883.jpg)

**Comment by KatsiarynaV** [comment]
Sometimes the switcher size is changing
![gif06](https://user-images.githubusercontent.com/68267190/127824576-ddcd1e08-edc3-4f65-9153-7df59aef1731.gif)

**Comment by KatsiarynaV** [comment]
Checked
