### ISSUE TITLE
Fixed info icon crop

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#17]
The icon looks a bit cropped from right side and the bottom. Please use an icon from here https://zpl.io/29d4Erl
<img width="137" alt="Screenshot 2021-07-30 at 00 47 39" src="https://user-images.githubusercontent.com/7249484/127570510-5ecd6521-2779-4d34-a6d1-5fafe7a4a0bd.png">

**Comment by KatsiarynaV** [comment]
Checked
