### ISSUE TITLE
Remove Back button

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#18]
Since we have the Dao Core App icon in sidebar, there's no need in Back button in the header. Please remove.
<img width="1010" alt="Screenshot at Jul 30 00-48-26" src="https://user-images.githubusercontent.com/7249484/127571066-91307fa4-f85f-4696-a6d4-cc5b232797e8.png">

**Comment by iscander01** [comment]
there is no back button in Dao Core App opened by clicking on the icon
![04774bbadf743484f3c3cb3693767559](https://user-images.githubusercontent.com/44571357/127626787-dc692fd2-843e-41cd-ab35-f09e56a48828.png)

**Comment by KatsiarynaV** [comment]
"Back" button was removed if opened using dao core button
