### ISSUE TITLE
Change order of sections in Governance and Allocation cards

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#19]
1. In "BEAMX Governance Token" section should be the following order (up to bottom)r:
- Distributed
- Available
- Locked

2. In "Investor allocation" section should be the following order (left to right):
- Locked
- Available
- Distributed

Design https://zpl.io/boJJRgm
<img width="819" alt="Screenshot at Aug 03 15-29-13" src="https://user-images.githubusercontent.com/7249484/128016005-2f26cdbc-1b60-4cdd-8c85-b4d697bc9624.png">

3. Check "zero states" of the graphs
Design https://zpl.io/aNYQYzn
- If possible, always show the number below the section. If not possible, show above.
- 0 should be hidden
![image](https://user-images.githubusercontent.com/7249484/128037166-8480903f-3719-484e-b876-07ed33f42fe9.png)

**Comment by KatsiarynaV** [comment]
![36](https://user-images.githubusercontent.com/68267190/128340010-d4316ffb-0604-4c76-9a89-96d2f505c665.jpg)

**Comment by KatsiarynaV** [comment]
Checked
