### ISSUE TITLE
Rename "Yearly/weekly reward" into "My yearly/weekly reward"

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#20]
Design 
https://zpl.io/VOLzGYj
https://zpl.io/29d4Erl
<img width="566" alt="Screenshot at Aug 03 15-19-51" src="https://user-images.githubusercontent.com/7249484/128014418-b3b6a0bf-6941-49f4-9d2c-f1f886bdd3ad.png">
<img width="609" alt="Screenshot at Aug 03 15-20-11" src="https://user-images.githubusercontent.com/7249484/128014428-ce923b0f-6037-48cb-876f-61ffa9337272.png">

**Comment by kazaryan-t** [comment]
Checked.
_My yearly reward_ was removed https://github.com/BeamMW/dao-core-app/issues/4#issuecomment-882307500.
