### ISSUE TITLE
Add "You can withdraw funds at any time" note

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#21]
On Dao Core deposit screen add "You can withdraw your funds at any time" note.
Design https://zpl.io/VOLzGYj
<img width="793" alt="Screenshot at Aug 03 13-32-00" src="https://user-images.githubusercontent.com/7249484/128001422-43d72b77-39fd-43ec-9238-c6f380fad4d0.png">

**Comment by AndreyDyakonov** [comment]
Checked
