### ISSUE TITLE
Add TVL on staking card (when there's nothing deposited yet)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#22]
Show TVL always, even if there's nothing deposited to the staking yet.
<img width="370" alt="Screenshot at Aug 03 13-43-01" src="https://user-images.githubusercontent.com/7249484/128002745-967f31c8-6023-4238-bb2b-05f8533da359.png">
Design https://zpl.io/29d4Erl

**Comment by KatsiarynaV** [comment]
After depositing or withdrawing funds my weekly rewards amount is updated after reopening the dapp
Deposit
![gif09](https://user-images.githubusercontent.com/68267190/128303226-02cf1450-be70-4671-9c94-5adecace98d2.gif)
Withdraw
![gif10](https://user-images.githubusercontent.com/68267190/128303232-07d78a4a-4dd4-4105-8122-ed37cbce778b.gif)

**Comment by iscander01** [comment]
weekly rewards updating will be fixed with https://github.com/BeamMW/beam-ui/issues/732

**Comment by KatsiarynaV** [comment]
Checked
