### ISSUE TITLE
Beam Governance card should have fixed weight (in full screen mode)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#27]
When wallet is open in full screen mode, BeamX Governance card shouldn't adapt it's size, it should remain the same. Only Staking card should adapt to screen's size.
Design https://zpl.io/adyOM9n

![image](https://user-images.githubusercontent.com/7249484/128339894-3ae59bf9-a135-4ef1-ae7b-5dd015a73698.png)
![image](https://user-images.githubusercontent.com/7249484/128339919-5bb6b2bc-f6fc-4a6b-926e-47ffbd6b7630.png)

**Comment by kazaryan-t** [comment]
Checked
