### ISSUE TITLE
BeamX DAO. Better layout and info for Deposit dialog.

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#29]
1. Add Max button
2. Add Available field
3. Add separator line and move Fee field below it
4. Make Fee amount in white color 

Current dialog
![image](https://user-images.githubusercontent.com/7249484/133890448-9775e6bd-c0ce-4933-90e9-046e4159d755.png)

New design https://zpl.io/VOLzGYj
![image](https://user-images.githubusercontent.com/7249484/133890446-5dc75b46-8d08-4fca-bb77-4db50c2cc459.png)

**Comment by iscander01** [comment]
1-3 wallet balance not available in DAPPs
4 done

**Comment by kazaryan-t** [comment]
Сhecked
