### ISSUE TITLE
BeamX DAO. Investor allocation section (mobile view)

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#35]
Add Investor allocation section (available only for investors). The section should be foldable 
https://zpl.io/V0Nq0LO

In Current height section, if number of days in brackets are less than 1, show "Current height (vesting starts today)"
If vesting already started, show "Current height (vesting started _date_)"
![image](https://user-images.githubusercontent.com/7249484/136239695-065d5add-ce74-4e9c-9614-251a791b8ba7.png)

**Comment by AndreyDyakonov** [comment]
Checked
