### ISSUE TITLE
Dao Core v1. Staking, Deposit

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#4]
***IMPORTANT:* Small updates in the designs, please check comments for this issue.**

1. Deposit dialog
https://zpl.io/VOLzGYj
![dao core depositv2](https://user-images.githubusercontent.com/7249484/124973638-60c4f400-e05e-11eb-815c-25a39cb578e6.jpg)

2. Deposit confirmation
https://zpl.io/VOLzwdQ
![dao core deposit confirmation](https://user-images.githubusercontent.com/7249484/124973246-df6d6180-e05d-11eb-8d3b-a40c3bb1df20.png)

3. Error state of input field is here https://zpl.io/2pRLWD8
![dao core deposit errorv2](https://user-images.githubusercontent.com/7249484/125081168-47708600-e0f8-11eb-870c-37f3df8cee91.jpg)

**Comment by iscander01** [comment]
3. Error state of input field - can`t to implement because data of the current balance is not available

**Comment by KatsiarynaV** [comment]
1. When choosing 6 month the amount is the same with 3 month
![gif01](https://user-images.githubusercontent.com/68267190/125931417-63753fbc-f9f7-4d7d-b2f0-e85adb863b09.gif)

2. The yearly reward should be 10-14 BEAMX
![07](https://user-images.githubusercontent.com/68267190/125938739-6b0687e9-ee82-45c8-8a7e-51de627e499f.jpg)

3. Make deposit confirmation as in the design
![03](https://user-images.githubusercontent.com/68267190/125938769-83b4671d-24eb-4812-a63b-5c941d6ad828.jpg)

4. Please display fee amount in second currency as "< 1 cent"
![08](https://user-images.githubusercontent.com/68267190/125938815-a791bcc3-3b82-40f1-b03f-3cd8b43fb8dc.jpg)
![10](https://user-images.githubusercontent.com/68267190/125938818-d2d4e39d-f0cd-47d4-95f4-bb00237c37f6.jpg)

**Comment by iscander01** [comment]
2. yearly reward was removed (edition from @beam-mw)
3. the transaction confirmation design is implemented inside the wallet (cannot be changed from the app)
4. done

**Comment by iscander01** [comment]
1. "6 M" was removed

**Comment by KatsiarynaV** [comment]
1. The switcher bug
![gif02](https://user-images.githubusercontent.com/68267190/126457353-30b7836e-5313-4189-9bd4-1fece9a8bbda.gif)

2. Please, place the text and the switcher as in the design
![18](https://user-images.githubusercontent.com/68267190/126454289-e26be33f-b5f6-4ed9-a2e8-d1f353bb2127.jpg)
![16](https://user-images.githubusercontent.com/68267190/126454292-588dcfb8-64fe-4607-8157-dcb9caacb1f1.jpg)

**Comment by chapati** [comment]
Please test confirmation dialogs on the latest build.

**Comment by KatsiarynaV** [comment]
1. Remove "USD" for fee amount in second currency
![22](https://user-images.githubusercontent.com/68267190/126945370-508819da-9d00-41f8-83b6-779732240f18.jpg)

2. When user makes first deposit the staking information appears after reopening the dapp
![gif04](https://user-images.githubusercontent.com/68267190/126945694-d84e157f-2948-48fe-8d5b-b45af039cdbf.gif)

**Comment by KatsiarynaV** [comment]
Checked
