### ISSUE TITLE
Dao Core v1. Investor allocation section

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#5]
Add Investor Allocation section on DAO Core screen (only visible for investors)
https://zpl.io/boJJRgm
<img width="1030" alt="Screenshot at Jul 08 21-19-25" src="https://user-images.githubusercontent.com/7249484/124971696-193d6880-e05c-11eb-9739-c53a8a2bdfdf.png">

**Comment by Denis-Asipenko** [comment]
when withdraw a small amount, it looks like  square
![image](https://user-images.githubusercontent.com/45556620/125791446-e2d2e8ed-0158-495d-ab3a-0f3733adc44e.png)
![image](https://user-images.githubusercontent.com/45556620/125791467-6997eba9-ea90-44ec-b976-c300e04ac7d6.png)

**Comment by Denis-Asipenko** [comment]
checked
