### ISSUE TITLE
Dao Core v1. Beam Governance section

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#6]
Add Beam Governance section on DAO Core screen
https://zpl.io/boJJRgm
<img width="1035" alt="Screenshot at Jul 08 21-17-50" src="https://user-images.githubusercontent.com/7249484/124971531-e4311600-e05b-11eb-8cd3-6954331638bf.png">

Public key dialog
https://zpl.io/agm1l49
![dao core public key](https://user-images.githubusercontent.com/7249484/124973062-a6cd8800-e05d-11eb-9fd9-9e7a08b2f931.png)

**Comment by Denis-Asipenko** [comment]
![image](https://user-images.githubusercontent.com/45556620/125793747-361e3c62-47a2-4d41-8c58-b457ce190cf3.png)

**Comment by AndreyDyakonov** [comment]
Beam Governance section on DAO Core screen:
in masternet "Show public key"
in zeplin "Show my public key"
![2021-07-19_10-34-32](https://user-images.githubusercontent.com/85252690/126121410-dfc03227-f890-4d65-b186-41ddfbf0b858.png)

Public key dialog:
in masternet "cancel"
in zeplin "close"
![2021-07-19_10-36-23](https://user-images.githubusercontent.com/85252690/126121853-17a5d6f2-1991-4f8c-b0e5-9e561c6513ee.png)

**Comment by AndreyDyakonov** [comment]
Checked
