### ISSUE TITLE
Dao Core v1. Staking section

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#8]
***IMPORTANT:* Small updates in the designs, please check comments for this issue.**

Add Staking section on DAO Core screen
https://zpl.io/boJJRgm
<img width="1047" alt="Screenshot at Jul 08 21-21-18" src="https://user-images.githubusercontent.com/7249484/124971931-5bff4080-e05c-11eb-907a-fb7611b79f93.png">

Staking widget states
nothing deposited yet
nothing farmed yet
already farmed
https://zpl.io/VOLQwDr
![staking-states](https://user-images.githubusercontent.com/7249484/124972000-6ae5f300-e05c-11eb-9e8d-aeeb8d8d12b4.png)

**Comment by kazaryan-t** [comment]
1. Please, change _Total value locked_ to **TVL**
Design - https://zpl.io/boJJRgm

![Beam Wallet Masternet 2021-07-16 12 52 41](https://user-images.githubusercontent.com/68247034/125930117-3e005da9-6645-4851-83e1-85707cf36802.png)

2. Add the popup as in the design when clicking on (i) button.

![Beam Wallet Masternet 2021-07-16 13 01 36](https://user-images.githubusercontent.com/68247034/125930884-4b04566b-83d0-41c2-86f3-7d673ae0578f.png)

![dao core v1 small info - 08 DAPPs - Zeplin - Googl](https://user-images.githubusercontent.com/68247034/125930893-a96877a2-ba55-4ebe-9325-37682c0d39b1.png)

**Comment by iscander01** [comment]
1. edit from @beam-mw 
2. duplicated issue https://github.com/BeamMW/dao-core-app/issues/2

**Comment by kazaryan-t** [comment]
Please, remove the section name **"Farmed"** if there is nothing farmed yet.

Design - https://zpl.io/VOLQwDr

![Beam Wallet Masternet 2021-07-19 09 57 59](https://user-images.githubusercontent.com/68247034/126116332-544426ca-fc88-4245-8e14-58e8ec737988.png)
![Dao Core v1  Staking section · Issue #8 · BeamMW_d](https://user-images.githubusercontent.com/68247034/126116335-be515324-ab10-4562-bf97-3b25b40990e1.png)

**Comment by kazaryan-t** [comment]
Checked.
