### ISSUE TITLE
Dao Core v1. Staking, Withdraw

### ISSUE THREAD

**Issue by alexandrashelenkova** [BeamMW/dao-core-app#9]
1. Withdraw dialog
https://zpl.io/agmMJZO
![dao core withdrawv2](https://user-images.githubusercontent.com/7249484/124973872-abdf0700-e05e-11eb-8f84-34eb800453e2.jpg)

2. Withdraw confirmation
https://zpl.io/bJ8YJ7W
![dao core withdraw confirmation](https://user-images.githubusercontent.com/7249484/124973898-b1d4e800-e05e-11eb-899d-897fc22929c6.png)

3. Error state of input field is here https://zpl.io/V0rGAXm
![dao core withdraw errorv2](https://user-images.githubusercontent.com/7249484/125081303-6ec75300-e0f8-11eb-88f2-1fda2e29dc01.jpg)

**Comment by KatsiarynaV** [comment]
1. Make withdraw confirmation as in the design
![01](https://user-images.githubusercontent.com/68267190/125938376-a4648798-1cd2-4b5b-88ea-5092b70217df.jpg)

2. Please display fee amount in second currency as "< 1 cent"
![09](https://user-images.githubusercontent.com/68267190/125938522-7372fa17-ab8e-48f1-b051-0169ab0abc43.jpg)
![10](https://user-images.githubusercontent.com/68267190/125938529-6ec8e0da-b9eb-4bae-91f2-4bccf8f2004c.jpg)

**Comment by iscander01** [comment]
1. the transaction confirmation design is implemented inside the wallet
2. done

**Comment by chapati** [comment]
As for 2:

* warning string also would be added if user is about to spend money.
* right button will be always "confirm". If user receives money - blue, if spends - magenta. 
* case of multiple assets is being designed now

**Comment by chapati** [comment]
Please test confirmation dialogs on the latest build.

**Comment by KatsiarynaV** [comment]
1, 3 - checked
2 - Withdraw confirmation dialog will be implemented and checked in #717 Dapps tx confirmations
